In [1]:
import numpy as np

## Creation of Array

In [2]:
a1 = np.arange(10)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2 = np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

In [5]:
a3 = np.array( (1,2,3,3))
a3

array([1, 2, 3, 3])

In [6]:
a4 = np.array("Python")
a4

array('Python', dtype='<U6')

In [7]:
a5 = np.ones(10)

In [8]:
a5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
type(a5)

numpy.ndarray

In [10]:
a5.shape

(10,)

In [11]:
a5.dtype

dtype('float64')

In [14]:
a5.size, a5.ndim

(10, 1)

In [15]:
a = np.array( (1,'abc'))

In [16]:
a

array(['1', 'abc'], dtype='<U11')

In [17]:
ra = np.random.rand(10)
ra

array([0.38286399, 0.62797679, 0.1631042 , 0.51063348, 0.41714315,
       0.24588735, 0.67424931, 0.98853449, 0.92357743, 0.00148889])

In [18]:
ra = np.random.randint(1,100,10)
ra

array([99, 11, 30, 81, 98, 51, 13,  5, 99,  2])

In [21]:
fa = np.full((5,5),9)
fa

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [23]:
[1,2,3] + [5]

[1, 2, 3, 5]

In [24]:
a = np.random.randint(1,10,5)
a

array([8, 8, 8, 2, 2])

In [25]:
a + 5

array([13, 13, 13,  7,  7])

In [30]:
a,i = np.linspace(1,10,3, retstep=True)
print(a)
print(i)

[ 1.   5.5 10. ]
4.5


## Indexing and slicing 

In [31]:
a = np.random.randint(1,100,10)
a

array([51, 61, 95, 39, 33, 22, 51, 43, 61, 96])

In [33]:
a[0], a[0:4]

(51, array([51, 61, 95, 39]))

In [34]:
for n in a:
     if n % 2 == 0:
             print(n)

22
96


### Boolean indexing

In [37]:
a % 2 == 0

array([False, False, False, False, False,  True, False, False, False,
        True])

In [38]:
a1 = np.array([1,2,3])

In [40]:
a1[ [True,False,True] ]

array([1, 3])

In [43]:
a [a % 2 == 0]   # get even numbers from array 

array([22, 96])

In [44]:
a[ a > 50 ]

array([51, 61, 95, 51, 61, 96])

In [46]:
dd = np.arange(9).reshape(3,3)

In [47]:
dd

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Array operations 

In [2]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
a1 * a2 

array([ 5, 12, 21, 32])

In [4]:
a1 + a2

array([ 6,  8, 10, 12])

In [5]:
a1.any()

True

In [6]:
ba = a1 > 10

In [7]:
ba

array([False, False, False, False])

In [8]:
ba.any()

False

In [10]:
(a1 % 2 == 0).any()

True

In [11]:
(a1 % 2 == 0).all()

False

In [12]:
marks = np.random.randint(1,100,10)

In [13]:
marks

array([71, 63,  1, 56, 45,  6, 10, 70, 81, 77])

In [17]:
marks.argmax()

8

In [18]:
marks.cumsum()

array([ 71, 134, 135, 191, 236, 242, 252, 322, 403, 480], dtype=int32)

In [19]:
marks.mean(), marks.max()

(48.0, 81)

In [20]:
marks.take([1,2,4])

array([63,  1, 45])

In [21]:
td = np.random.randint(1,10,9).reshape(3,3)
td

array([[3, 7, 3],
       [1, 7, 8],
       [6, 5, 1]])

In [29]:
td.max(), td.max(axis=0), td.max(axis=1)

(8, array([6, 7, 8]), array([7, 8, 6]))

## Copy vs. View 

In [30]:
a = np.random.randint(1,10,10)
b = a[0:5]
a,b

(array([8, 1, 7, 6, 7, 4, 6, 2, 6, 1]), array([8, 1, 7, 6, 7]))

In [31]:
b[0] = 1
a

array([1, 1, 7, 6, 7, 4, 6, 2, 6, 1])

In [32]:
c = a.copy()
c[0] = 11

array([1, 1, 7, 6, 7, 4, 6, 2, 6, 1])

In [34]:
c

array([11,  1,  7,  6,  7,  4,  6,  2,  6,  1])

In [35]:
td

array([[3, 7, 3],
       [1, 7, 8],
       [6, 5, 1]])

In [39]:
td.flatten(order='F')  # Column major

array([3, 1, 6, 7, 7, 5, 3, 8, 1])

In [40]:
td.flatten(order='C')  # Row Major

array([3, 7, 3, 1, 7, 8, 6, 5, 1])

In [42]:
for n in td.flat:
    print(n,end= ' ')

3 7 3 1 7 8 6 5 1 

In [72]:
a1 = np.arange(5)
a2 = np.arange(5)

In [77]:
np.add(a1,a2)

array([ 0,  3,  6,  9, 12])

In [74]:
a1

array([0, 1, 2, 3, 4])

In [75]:
a2

array([0, 2, 4, 6, 8])

In [78]:
td

array([[3, 7, 3],
       [1, 7, 8],
       [6, 5, 1]])

In [81]:
td.mean(axis=1)

array([4.33333333, 5.33333333, 4.        ])

In [82]:
oa = np.random.randint(1,10,10)

In [83]:
na = oa.reshape(2,5)  # Take a view that is 2d 

In [84]:
oa

array([4, 3, 5, 2, 2, 3, 1, 3, 3, 2])

In [89]:
oa.resize(5,2)

In [90]:
oa

array([[10,  3],
       [ 5,  2],
       [ 2,  3],
       [ 1,  3],
       [ 3,  2]])

In [86]:
na[0][0] = 10

In [87]:
oa

array([10,  3,  5,  2,  2,  3,  1,  3,  3,  2])

In [88]:
td.ravel()

array([3, 7, 3, 1, 7, 8, 6, 5, 1])

In [91]:
oa + 2

array([[12,  5],
       [ 7,  4],
       [ 4,  5],
       [ 3,  5],
       [ 5,  4]])

In [92]:
oa += 2

In [93]:
oa

array([[12,  5],
       [ 7,  4],
       [ 4,  5],
       [ 3,  5],
       [ 5,  4]])

In [94]:
oa

array([[12,  5],
       [ 7,  4],
       [ 4,  5],
       [ 3,  5],
       [ 5,  4]])

In [95]:
oa + 2

array([[14,  7],
       [ 9,  6],
       [ 6,  7],
       [ 5,  7],
       [ 7,  6]])

In [96]:
oa

array([[12,  5],
       [ 7,  4],
       [ 4,  5],
       [ 3,  5],
       [ 5,  4]])

In [ ]:
oa += 2