In [1]:
import numpy as np

## Creation of Array

In [2]:
a1 = np.arange(10)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2 = np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

In [5]:
a3 = np.array( (1,2,3,3))
a3

array([1, 2, 3, 3])

In [6]:
a4 = np.array("Python")
a4

array('Python', dtype='<U6')

In [7]:
a5 = np.ones(10)

In [8]:
a5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
type(a5)

numpy.ndarray

In [10]:
a5.shape

(10,)

In [11]:
a5.dtype

dtype('float64')

In [14]:
a5.size, a5.ndim

(10, 1)

In [15]:
a = np.array( (1,'abc'))

In [16]:
a

array(['1', 'abc'], dtype='<U11')

In [17]:
ra = np.random.rand(10)
ra

array([0.38286399, 0.62797679, 0.1631042 , 0.51063348, 0.41714315,
       0.24588735, 0.67424931, 0.98853449, 0.92357743, 0.00148889])

In [18]:
ra = np.random.randint(1,100,10)
ra

array([99, 11, 30, 81, 98, 51, 13,  5, 99,  2])

In [21]:
fa = np.full((5,5),9)
fa

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [23]:
[1,2,3] + [5]

[1, 2, 3, 5]

In [24]:
a = np.random.randint(1,10,5)
a

array([8, 8, 8, 2, 2])

In [25]:
a + 5

array([13, 13, 13,  7,  7])

In [30]:
a,i = np.linspace(1,10,3, retstep=True)
print(a)
print(i)

[ 1.   5.5 10. ]
4.5


## Indexing and slicing 

In [31]:
a = np.random.randint(1,100,10)
a

array([51, 61, 95, 39, 33, 22, 51, 43, 61, 96])

In [33]:
a[0], a[0:4]

(51, array([51, 61, 95, 39]))

In [34]:
for n in a:
     if n % 2 == 0:
             print(n)

22
96


### Boolean indexing

In [37]:
a % 2 == 0

array([False, False, False, False, False,  True, False, False, False,
        True])

In [38]:
a1 = np.array([1,2,3])

In [40]:
a1[ [True,False,True] ]

array([1, 3])

In [43]:
a [a % 2 == 0]   # get even numbers from array 

array([22, 96])

In [44]:
a[ a > 50 ]

array([51, 61, 95, 51, 61, 96])

In [46]:
dd = np.arange(9).reshape(3,3)

In [47]:
dd

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])